parameters:
#    back_office_admin.example.class: BackOffice\AdminBundle\Example

services:
#    back_office_admin.example:
#        class: %back_office_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
