front_office_payment:
    resource: "@FrontOfficePaymentBundle/Resources/config/routing.yml"
    prefix:   /

front_office_rating:
    resource: "@FrontOfficeRatingBundle/Resources/config/routing.yml"
    prefix:   /


front_office_user:
    resource: "@FrontOfficeUserBundle/Resources/config/routing.yml"
    prefix:   /

back_office_admin:
    resource: "@BackOfficeAdminBundle/Resources/config/routing.yml"
    prefix:   /

front_office_optimus:
    resource: "@FrontOfficeOptimusBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
    
payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"

payum_authorize:
    resource: "@PayumBundle/Resources/config/routing/authorize.xml"

payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"
    
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"