<?php

namespace FrontOffice\OptimusBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigNotifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigNotifRepository extends EntityRepository
{
}
