<?php

namespace FrontOffice\OptimusBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryEventRepository extends EntityRepository {

    public function historyEventLoadAjax($id,$last_id) {

        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT he, u "
                        . "FROM FrontOfficeOptimusBundle:HistoryEvent he LEFT JOIN he.user u"
                        . " where u = :id"
                        . " ORDER BY he.date DESC"
                )->setParameter('id', $id)
                ->setMaxResults(1)
                ->setFirstResult($last_id);
        return $events = $query->getArrayResult();
    }
}
