<?php

namespace FrontOffice\OptimusBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryClubRepository extends EntityRepository {
   
    public function historyClubLoadAjax($id,$last_id) {

        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT hc, u "
                        . "FROM FrontOfficeOptimusBundle:HistoryClub hc LEFT JOIN hc.user u"
                        . " where u = :id"
                        . " ORDER BY hc.date DESC"
                )->setParameter('id', $id)
                ->setMaxResults(1)
                ->setFirstResult($last_id);
        return $events = $query->getArrayResult();
    }

}
