<?php

namespace FrontOffice\OptimusBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends EntityRepository {

    public function getMembers($id) {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select(array('m'))
                ->from('FrontOffice\OptimusBundle\Entity\Member', 'm')
                ->Join('FrontOffice\OptimusBundle\Entity\Club', 'c', "WITH", 'm.clubad = c.id')
                ->where('m.confirmed = 1')
                ->andWhere('c.id = :id')
               
                ->setParameter('id', $id);
               
        return $qb->getQuery()->getResult();
    }

    public function getMembersRequest($id, $idc) {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select(array('m'))
                ->from('FrontOffice\OptimusBundle\Entity\Member', 'm')
                ->Join('FrontOffice\OptimusBundle\Entity\Club', 'c', "WITH", 'm.clubad = c.id')
                ->where('m.confirmed = 0')
                ->andWhere('c.id = :id')
                ->andWhere('c.createur = :idc')
                ->setParameter('id', $id)
                ->setParameter('idc', $idc);
        return $qb->getQuery()->getResult();
    }

}
