<?php
namespace FrontOffice\OptimusBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends EntityRepository
{
    public function getPhotoClub($club)
    {
        $qb=$this->getEntityManager()->createQueryBuilder();
     $album=$qb->select('a')
                     ->from("FrontOfficeOptimusBundle:Album", 'a')
                     ->where("a.club = :club")
                     ->setParameter('club', $club)
                     ->getQuery()->getResult();
    $tab=array();
    if($album)
    {
     foreach ($album as $a) {
      $tab[]=$a->getId();
     }
     $qb=$this->getEntityManager()->createQueryBuilder();
     $photo=$qb->select('p')
             ->from('FrontOfficeOptimusBundle:Photo', 'p')
             ->where($qb->expr()->In('p.album', $tab))
             ->setMaxResults('6')
             ->getQuery()->getResult();
      return $photo;
    }
   }
    
    public function getPhotoUser($user)
    {
        $qb=$this->getEntityManager()->createQueryBuilder();
     $album=$qb->select('a')
                     ->from("FrontOfficeOptimusBundle:Album", 'a')
                     ->where("a.utilisateur = :user")
                     ->setParameter('user', $user)
                     ->getQuery()->getResult();
    $tab=array();
    if($album)
    {
     foreach ($album as $a) {
      $tab[]=$a->getId();
     }
     $qb=$this->getEntityManager()->createQueryBuilder();
     $photo=$qb->select('p')
             ->from('FrontOfficeOptimusBundle:Photo', 'p')
             ->where($qb->expr()->In('p.album', $tab))
             ->setMaxResults('6')
             ->getQuery()->getResult();
      return $photo;
    }
   }
    public function getPhotoAlbum($id)
    {
        $qb=$this->getEntityManager()->createQueryBuilder();
     $qb->select('p')
                     ->from("FrontOfficeOptimusBundle:Photo", 'p')
                     ->Join ("FrontOfficeOptimusBundle:Album", 'a')
                     ->where("p.album = a")
                     ->andWhere("a.id = :id")
                     ->setParameter('id', $id)
                     ->getQuery()->getArrayResult();
    
    }
    
    
}
