<?php

namespace FrontOffice\OptimusBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProgramRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramRepository extends EntityRepository
{
    public function getProgramJour($id) {

        $em = $this->getEntityManager();
        $dt = new \Datetime();
        $dt = $dt->modify('+ 1 days');
        $dt2 = new \DateTime();
        $dt2 = $dt2->modify('+ 2 days');
        $query = $em->createQuery("SELECT program "
                        . "FROM FrontOfficeOptimusBundle:Program program"
                        . " where program.clubp = :id and program.datedebut BETWEEN  '" . $dt->format("Y-m-d") . " 00:00:00' and '" . $dt2->format("Y-m-d") . " 23:59:59'"
                )->setParameter('id', $id);

        return $programs = $query->getResult();
    }
}
