parameters:
#    front_office_rating.example.class: FrontOffice\RatingBundle\Example

services:
#    front_office_rating.example:
#        class: %front_office_rating.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
